name: Build y Test Infinity Parfum

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test Envio
        run: |
          echo ">> Compilando Envio"
          mvn -f Envio/pom.xml clean install

      - name: Build and test Pago
        run: |
          echo ">> Compilando Pago"
          mvn -f Pago/pom.xml clean install

      - name: Build and test Pedidos
        run: |
          echo ">> Compilando Pedidos"
          mvn -f Pedidos/pom.xml clean install

      - name: Build and test Productos
        run: |
          echo ">> Compilando Productos"
          mvn -f Productos/pom.xml clean install

      - name: Build and test Usuario
        run: |
          echo ">> Compilando Usuario"
          mvn -f Usuario/pom.xml clean install
